services:
  - type: web
    name: fake-reviews-detection
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential gfortran libatlas-base-dev && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    plan: free